service: sls-node-test

#frameworkVersion: ">=1.34.0"

provider:
  name: aws
  runtime: provided
  timeout: 60
  environment:
    SLSMIDDLEWARES: test-middleware

functions:
  hello:
    handler: handler.hello
    layers:
      - arn:aws:lambda:us-east-1:377024778620:layer:testRuntime:7
      - {Ref: TestMiddlewareLambdaLayer}
    events:
      - http:
          path: /
          method: GET

layers:
  testMiddleware:
    path: middleware
