service: serverless-open-runtime

#frameworkVersion: ">=1.34.0"

provider:
  name: aws

package:
  exclude:
    - 'node-v*-linux-x64.tar.xz'
    - '**/*.go'
    - '**/Makefile'
    - '**/package*.json'

layers:
  open-runtime:
    path: bootstrap
  open-runtime-nodejs:
    path: nodejs
resources:
  Outputs:
    OpenRuntimeLambdaLayerExport:
        Value:
          Ref: OpenDashruntimeLambdaLayer
        Export:
          Name: OpenRuntimeLambdaLayer
    OpenRuntimeNodejsLambdaLayerExport:
        Value:
          Ref: OpenDashruntimeDashnodejsLambdaLayer
        Export:
          Name: OpenRuntimeNodejsLambdaLayer
