service: serverless-open-runtime

#frameworkVersion: ">=1.34.0"

provider:
  name: aws

package:
  exclude:
    - 'node-v*-linux-x64.tar.xz'

layers:
  testRuntime: # TODO rename (holding off bc of the permanant nature of layers)
    path: layer
